_format_version: "2.1"

services:
  - name: echo-server
    url: http://backend
    routes:
      - name: echo
        paths:
          - /echo

# plugins section
plugins:
  - name: request-transformer
    config:
      remove:
        headers:
          - x-toremove
        querystring:
          - q-toremove
      add:
        headers:
          - x-new-header:x-new-header
        querystring:
          - new-param:new-param
