_format_version: "2.1"

services:
  - name: echo-server
    url: http://backend
    # url: http://10.10.10.100:8000
    routes:
      - name: echo
        paths:
          - /echo

# plugins section
plugins:
  - name: response-transformer
    config:
      remove:
        headers:
          - x-toremove
        json:
          - host
          - http
      add:
        headers:
          - h1:v2
          - h2:v1
        json:
          - string:new_json
          - number:123
          - boolean:false
        json_types:
          - string
          - number
          - boolean
      append:
        headers:
          - x-existing-header:append_existing_header
          - x-another-header:append_another_header
          - h1:test
